insert into IDN_RESOURCE (
RESOURCE_ID, RESOURCE_NAME, TIME_CREATED, TOKEN_ID, RESOURCE_OWNER_ID,
  RESOURCE_SERVER_ID, RESOURCE_OWNER_NAME, TENANT_ID) VALUES
('1', 'dewniRS', '2017-11-06 10:41:09','1', '1', '1', 'dewniRO', '1');

insert into IDN_RESOURCE (
  RESOURCE_ID, RESOURCE_NAME, TIME_CREATED, TOKEN_ID, RESOURCE_OWNER_ID,
  RESOURCE_SERVER_ID, RESOURCE_OWNER_NAME, TENANT_ID) VALUES
  ('2', 'dewniRS2', '2017-11-07 10:41:08','2', '2', '2', 'dewniRO2', '2');

DELETE FROM IDN_RESOURCE
WHERE ID=2;

INSERT INTO IDN_OAUTH2_SCOPE (NAME, DESCRIPTION) VALUES
  ('scope1', 'scope1 description');
INSERT INTO IDN_OAUTH2_SCOPE (NAME, DESCRIPTION) VALUES
  ('scope2', 'scope2 description');
INSERT INTO IDN_OAUTH2_SCOPE (NAME, DESCRIPTION) VALUES
  ('scope22', 'scope22 description');

INSERT INTO IDN_RESOURCE_SCOPE (RESOURCE_IDENTITY, SCOPE_ID) VALUES
  ((SELECT ID FROM IDN_RESOURCE WHERE ID= '1'),
   (SELECT SCOPE_ID FROM IDN_OAUTH2_SCOPE WHERE IDN_OAUTH2_SCOPE.SCOPE_ID= '1'))
;
INSERT INTO IDN_RESOURCE_SCOPE (RESOURCE_IDENTITY, SCOPE_ID) VALUES
  ((SELECT ID FROM IDN_RESOURCE WHERE RESOURCE_ID= '2'),
   (SELECT SCOPE_ID FROM IDN_OAUTH2_SCOPE WHERE IDN_OAUTH2_SCOPE.NAME= 'scope2'))
;
INSERT INTO IDN_RESOURCE_SCOPE (RESOURCE_IDENTITY, SCOPE_ID) VALUES
  ((SELECT ID FROM IDN_RESOURCE WHERE RESOURCE_ID= '2'),
   (SELECT SCOPE_ID FROM IDN_OAUTH2_SCOPE WHERE IDN_OAUTH2_SCOPE.NAME= 'scope22'))
;


INSERT INTO IDN_RESOURCE_META_DATA (RESOURCE_IDENTITY, PROPERTY_KEY, PROPERTY_VALUE)
VALUES ((SELECT ID FROM IDN_RESOURCE WHERE ID= '1'),'1', '1');
INSERT INTO IDN_RESOURCE_META_DATA (RESOURCE_IDENTITY, PROPERTY_KEY, PROPERTY_VALUE)
VALUES ((SELECT ID FROM IDN_RESOURCE WHERE RESOURCE_ID= '2'),'2', '2');


INSERT INTO IDN_PERMISSION_TICKET (PT, TIME_CREATED, VALIDITY_PERIOD, TICKET_STATE)
VALUES ('1234', '2017-11-06 10:41:09', 360000, 'ACTIVE');

INSERT INTO IDN_PT_RESOURCE (PT_RESOURCE_ID, PT_ID) VALUES
  ((SELECT ID FROM IDN_RESOURCE WHERE IDN_RESOURCE.ID= 3
   ),(SELECT ID FROM IDN_PERMISSION_TICKET WHERE ID= 1));

INSERT INTO IDN_PT_RESOURCE_SCOPE (PT_RESOURCE_ID, PT_SCOPE_ID)
    VALUES ((SELECT ID FROM IDN_PT_RESOURCE WHERE ID= 1),
            (SELECT SCOPE_ID FROM IDN_OAUTH2_SCOPE WHERE SCOPE_ID= 1 ));



--   INSERT INTO IDN_PT_RESOURCE_SCOPE
-- (PT_RESOURCE_ID, PT_SCOPE_ID) VALUES ('hhy', (SELECT SCOPE_ID FROM IDN_OAUTH2_SCOPE WHERE NAME = ?))